In [1]:
import numpy as np

# Глава 2. Векторы. Часть 1

## Сложение векторов

In [2]:
# складываем вектора-строки:
a = np.array([1, 2, 3])
b = np.array([3, 2, 1])
print(a + b)

[4 4 4]


In [3]:
# складываем вектора-столбцы:
a = np.array([[1, 2, 3]]).T
b = np.array([[3, 2, 1]]).T
print(a + b)

[[4]
 [4]
 [4]]


### Транслирование

In [4]:
# складываем вектор-строку с вектором-столбцом:
v = np.array([[4, 5, 6]])
w = np.array([[10, 20, 30]]).T
print(v + w)

[[14 15 16]
 [24 25 26]
 [34 35 36]]


In [5]:
# изменим ориентацию векторов:
v = np.array([[4, 5, 6]]).T
w = np.array([[10, 20, 30]])
print(v + w)

[[14 24 34]
 [15 25 35]
 [16 26 36]]


In [6]:
# сложим вектора разного размера
v = np.array([[4, 5, 6]]).T
w = np.array([[10, 20, 30, 40]])
print(v + w) # сложение при помощи транслирования
print((v + w).shape)

[[14 24 34 44]
 [15 25 35 45]
 [16 26 36 46]]
(3, 4)


In [7]:
# изменим ориентацию векторов
v = np.array([[4, 5, 6]])
w = np.array([[10, 20, 30, 40]]).T
print(v + w) # сложение при помощи транслирования
print((v + w).shape)

[[14 15 16]
 [24 25 26]
 [34 35 36]
 [44 45 46]]
(4, 3)


## Умножение вектора на скаляр

In [8]:
s = 2
a = [3, 4, 5]
b = np.array(a)
c = np.array([a]).T
print(a * s)
print(b * s)
print(c * s)

[3, 4, 5, 3, 4, 5]
[ 6  8 10]
[[ 6]
 [ 8]
 [10]]


## Сложение скаляра с вектором

Это действие в формально в линейной алгебре не определено, однако программы числовой обработки позволяют складывать скаляры с векторами:

In [9]:
s = 2
v = np.array([3, 6])
v_t = np.array([[3, 6]]).T
print(s + v)
print(s + v_t)

[5 8]
[[5]
 [8]]


Быдо выполнено прибавление скаляра к каждому элементу вектора.

## Геометрическое умножение вектора на скаляр

In [10]:
s = 0.25
v = np.array([4, 8, 10])
v_t = np.array([[4, 8, 10]]).T
print(s * v)
print(s * v_t)

[1.  2.  2.5]
[[1. ]
 [2. ]
 [2.5]]


#### Усреднение векторов

Это умножение вектора на скаляр в сочетании со сложение векторов:

In [11]:
v = np.array([[1, 2, 3]]).T
u = np.array([[2, 4, 6]]).T
n = len(v)
m = (v + u) * (1/n)
m

array([[1.],
       [2.],
       [3.]])

## Модуль вектора и единичные векторы

In [12]:
# вычислим норму (модуль) вектора:
v = np.array([1, 2, 3, 7, 8, 9])
v_dim = len(v)
v_mag = np.linalg.norm(v)
print(f"Размерность массива = {v_dim}", f"Модуль вектора = {v_mag}", sep="\n")

Размерность массива = 6
Модуль вектора = 14.422205101855956


In [13]:
# Вычислим единичные вектор:
v_one = v * (1 / v_mag)
v_one

array([0.06933752, 0.13867505, 0.20801257, 0.48536267, 0.5547002 ,
       0.62403772])

In [14]:
# Проверочка:
np.linalg.norm(v_one)

1.0

## Точечное произведение векторов

**Точечное произведение** - это одно число, которое представляет информацию о взаимосвязи между двумя векторами.

Точечное произведение допустимо только между двумя векторами одинаковой размерности.

In [15]:
v = np.array([1, 2, 3, 4])
w = np.array([5, 6, 7, 8])
np.dot(v, w)

70

**Свойство:** умножение одного вектора на скаляр шкалирует точечное произведение на то же число:

In [16]:
s = 10
np.dot(s * v, w)

700

Точечные произведения лежат в основе умножения матриц.

In [17]:
# изменим ориентацию второго вектора
v = np.array([1, 2, 3, 4])
w = np.array([[5, 6, 7, 8]]).T
np.dot(v, w)

array([70])

In [18]:
# изменим ориентацию первого вектора
v = np.array([[1, 2, 3, 4]]).T
w = np.array([5, 6, 7, 8])
np.dot(v, w)

ValueError: shapes (4,1) and (4,) not aligned: 1 (dim 1) != 4 (dim 0)

### Свойство дистрибутивности точечного произведения:

In [19]:
a = np.array([0, 1, 2])
b = np.array([3, 5, 8])
c = np.array([13, 21, 34])
# точечное произведение дистрибутивно:
res1 = np.dot(a, b + c)
res2 = np.dot(a, b) + np.dot(a, c)
res1 == res2

True

## Адамарово умножение

In [20]:
a = np.array([5, 4, 8, 2])
b = np.array([1, 0, .5, 2])
a * b

array([5., 0., 4., 4.])

## Внешнее произведение

In [21]:
a = np.array([5, 4, 8, 2])
b = np.array([1, 0, .5])
np.outer(a, b)

array([[5. , 0. , 2.5],
       [4. , 0. , 2. ],
       [8. , 0. , 4. ],
       [2. , 0. , 1. ]])

In [22]:
a = np.array([5, 4, 8, 2])
b = np.array([1, 0, .5])
np.outer(b, a)

array([[5. , 4. , 8. , 2. ],
       [0. , 0. , 0. , 0. ],
       [2.5, 2. , 4. , 1. ]])

## Ортогональное разложение векторов