# Домашнее задание "Линейная алгебра. Матрицы".

## Уровень 0:

### Задание 1

In [1]:
import numpy as np

1. Создайте матрицу 3 на 3, заполненную числами от 1 до 9

In [2]:
# Создаем матрицу 3 х 3
A = np.matrix("1 4 7; 2 5 8; 3 6 9")
A

matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

2. Прибавьте к ней матрицу с единицами на диагонали

In [3]:
B = np.eye(3)
B

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
A = A + B
A

matrix([[ 2.,  4.,  7.],
        [ 2.,  6.,  8.],
        [ 3.,  6., 10.]])

3. Умножьте полученную матрицу на вектор (1, 2, 3)

In [5]:
v = np.array([1, 2, 3])
v

array([1, 2, 3])

In [6]:
np.dot(A, v)

matrix([[31., 38., 45.]])

4. Вычислить транспонированную матрицу от полученной в результате прибавления матрицы

In [8]:
A_transp = A.T
A_transp

matrix([[ 2.,  2.,  3.],
        [ 4.,  6.,  6.],
        [ 7.,  8., 10.]])

5. Посчитайте обратную матрицу к полученной в результате прибавления матрице

In [9]:
A_inv = np.linalg.inv(A)
A_inv

matrix([[-6. , -1. ,  5. ],
        [-2. ,  0.5,  1. ],
        [ 3. ,  0. , -2. ]])

In [10]:
# проверка:
A @ A_inv

matrix([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
        [-3.55271368e-15,  0.00000000e+00,  1.00000000e+00]])

## Уровень 1:

### Задание 2

Найдите собственные значения и собственные вектора матрицы:

m = np.array([[2, 2],
              [1, 3]])

In [12]:
m = np.array([[2, 2], [1, 3]])
m

array([[2, 2],
       [1, 3]])

In [22]:
# Собственные значения матрицы:
print(f"Собственные значения матрицы m: {np.linalg.eigvals(m)}")

Собственные значения матрицы m: [1. 4.]


In [23]:
# Собственные вектора матрицы:
res = np.linalg.eig(m)[1].T
# Первый вектор:
print(f"Первый собственный вектор: {res[0]}")
print(f"Второй собственный вектор: {res[1]}")

Первый собственный вектор: [-0.89442719  0.4472136 ]
Второй собственный вектор: [-0.70710678 -0.70710678]


### Задание 3

Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0.

P.S. Матрица должна быть ненулевой и размерностью не менее 2!

In [24]:
A = np.matrix("2 3; 3 5")
A

matrix([[2, 3],
        [3, 5]])

In [34]:
det = np.linalg.det(A)
print(f"Определитель матрицы A = {det.round()}")

Определитель матрицы A = 1.0


In [35]:
r = np.linalg.matrix_rank(A)
print(f"Ранг матрицы А = {r}")

Ранг матрицы А = 2
